### ISSUE TITLE
Tinted vignettes

### ISSUE THREAD

**Issue by moi90** [SciViews/zooimage#3]
Hi, can you explain how the vignette tinting was implemented?

**Comment by phgrosjean** [comment]
Hello,

We use three images: the optical density calibrated image (OD), the visually enhanced image, and the mask. Those three images are combined as an RGB image so that different tints of colours appear for objects of interest versus background, while enhancing the shadows and shades of (initial grays) all around the image. Also, the tinted vignettes are decomposable into OD / visual / mask without lost of information, and the scale is added too.

In comparison with the ancien grayscale vignettes, it has two benefits: (1) better visual -differentiation of objects versus background and enhanced details- for taxonomists that have to label objects by visual inspection, and (2) the possibility to reconstruct OD + mask (for further image analysis), or OD alone (for deep learning CNN algorithms).

**Comment by moi90** [comment]
Thanks for the explanation!
Some further questions, if you don't mind:
- How is the OD-calibrated image calculated? Is this simply the logarithm of the raw gray values?
- What is the "visually enhanced image"?

**Comment by phgrosjean** [comment]
Calibration of OD images is done by using neutral gray photographic filters of known OD (0.25, 0.5 and 1). The same profile is applied to the picture. This way, gray levels on the OD image always match the same transparency in the original particles. The visually enhanced image is an image where the LUT (lookup table) is modified to enhance details in very transparent areas (thus, pixels close the the background). It reveals details useful for the taxonomist to identify the item.

**Comment by moi90** [comment]
Ah, I see. Thank you for explaining!

I think I got my questions answered, so I will close the issue.
